spring:
  application:
    name: spring-boot-graphql
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    data-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
